import { MigrationInterface, QueryRunner } from "typeorm";

export class TestMigration1763045835654 implements MigrationInterface {
    name = 'TestMigration1763045835654'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "layer_feature" DROP CONSTRAINT "layer_feature_layer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "layer" DROP CONSTRAINT "layer_updated_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "layer" DROP CONSTRAINT "layer_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "layer" DROP CONSTRAINT "layer_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "page" DROP CONSTRAINT "page_updated_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "page" DROP CONSTRAINT "page_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_page" DROP CONSTRAINT "role_page_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_page" DROP CONSTRAINT "role_page_page_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_page" DROP CONSTRAINT "role_page_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "role_updated_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "role_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "user_role_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "user_role_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "user_role_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "user_updated_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "user_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "map" DROP CONSTRAINT "map_updated_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "map" DROP CONSTRAINT "map_created_by_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_layer_feature_geometry"`);
        await queryRunner.query(`DROP INDEX "public"."idx_layer_bbox"`);
        await queryRunner.query(`COMMENT ON TABLE "layer_feature" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "layer" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "page" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "role_page" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "role" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "user_role" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "user" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "map" IS NULL`);
        await queryRunner.query(`ALTER TABLE "layer_feature" ALTER COLUMN "properties" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "layer_feature" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "layer" ALTER COLUMN "style" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "layer" ALTER COLUMN "style" SET DEFAULT '{"fillColor":"#3388ff","fillOpacity":0.5,"strokeColor":"#0066cc","strokeWidth":2,"iconUrl":null}'`);
        await queryRunner.query(`ALTER TABLE "layer" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "layer" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "page" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "page" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role_page" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "map" ALTER COLUMN "map_type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "map" ALTER COLUMN "settings" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "map" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "map" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_layer_feature_geometry" ON "layer_feature" ("geometry") `);
        await queryRunner.query(`CREATE INDEX "idx_layer_bbox" ON "layer" ("bbox_geometry") `);
        await queryRunner.query(`ALTER TABLE "layer_feature" ADD CONSTRAINT "FK_cb28c0cdd1df7319ac81f4e6832" FOREIGN KEY ("layer_id") REFERENCES "layer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layer" ADD CONSTRAINT "FK_397017cf52146c923a8f25909ae" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layer" ADD CONSTRAINT "FK_8e469c3847df56939ce3e8461cb" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layer" ADD CONSTRAINT "FK_ea057aa4d58211a5c236dac7c60" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page" ADD CONSTRAINT "FK_9b61a9afdaa3247f401f980f447" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page" ADD CONSTRAINT "FK_0c1f1134e68bed58c5d497490d1" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_page" ADD CONSTRAINT "FK_47313398359bd8936363c45cfbd" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_page" ADD CONSTRAINT "FK_cd45eca317df9969033c9413c7c" FOREIGN KEY ("page_id") REFERENCES "page"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_page" ADD CONSTRAINT "FK_0a9e3844f1ff06324363a40dde3" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "FK_04a09925beea59e864e921db4a1" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "FK_858c871a036f61e56e2740c7cda" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_0d65d1750949a41a47c174ed36a" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_d2f5e343630bd8b7e1e7534e82e" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_6bfae5ab9f39212d5b6ad0276b1" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "map" ADD CONSTRAINT "FK_67dd49f3e4d367ea9229cdb8648" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "map" ADD CONSTRAINT "FK_a4cf084a5eab12362909cb39211" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "map" DROP CONSTRAINT "FK_a4cf084a5eab12362909cb39211"`);
        await queryRunner.query(`ALTER TABLE "map" DROP CONSTRAINT "FK_67dd49f3e4d367ea9229cdb8648"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_6bfae5ab9f39212d5b6ad0276b1"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_d2f5e343630bd8b7e1e7534e82e"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_0d65d1750949a41a47c174ed36a"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "FK_858c871a036f61e56e2740c7cda"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "FK_04a09925beea59e864e921db4a1"`);
        await queryRunner.query(`ALTER TABLE "role_page" DROP CONSTRAINT "FK_0a9e3844f1ff06324363a40dde3"`);
        await queryRunner.query(`ALTER TABLE "role_page" DROP CONSTRAINT "FK_cd45eca317df9969033c9413c7c"`);
        await queryRunner.query(`ALTER TABLE "role_page" DROP CONSTRAINT "FK_47313398359bd8936363c45cfbd"`);
        await queryRunner.query(`ALTER TABLE "page" DROP CONSTRAINT "FK_0c1f1134e68bed58c5d497490d1"`);
        await queryRunner.query(`ALTER TABLE "page" DROP CONSTRAINT "FK_9b61a9afdaa3247f401f980f447"`);
        await queryRunner.query(`ALTER TABLE "layer" DROP CONSTRAINT "FK_ea057aa4d58211a5c236dac7c60"`);
        await queryRunner.query(`ALTER TABLE "layer" DROP CONSTRAINT "FK_8e469c3847df56939ce3e8461cb"`);
        await queryRunner.query(`ALTER TABLE "layer" DROP CONSTRAINT "FK_397017cf52146c923a8f25909ae"`);
        await queryRunner.query(`ALTER TABLE "layer_feature" DROP CONSTRAINT "FK_cb28c0cdd1df7319ac81f4e6832"`);
        await queryRunner.query(`DROP INDEX "public"."idx_layer_bbox"`);
        await queryRunner.query(`DROP INDEX "public"."idx_layer_feature_geometry"`);
        await queryRunner.query(`ALTER TABLE "map" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "map" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "map" ALTER COLUMN "settings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "map" ALTER COLUMN "map_type" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "role" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "role" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "role_page" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "page" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "page" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "layer" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "layer" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "layer" ALTER COLUMN "style" SET DEFAULT '{"iconUrl": null, "fillColor": "#3388ff", "fillOpacity": 0.5, "strokeColor": "#0066cc", "strokeWidth": 2}'`);
        await queryRunner.query(`ALTER TABLE "layer" ALTER COLUMN "style" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "layer_feature" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "layer_feature" ALTER COLUMN "properties" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON TABLE "map" IS 'ArcGIS WebMap configurations with single default constraint'`);
        await queryRunner.query(`COMMENT ON TABLE "user" IS 'Platform user with authentication and audit capabilities'`);
        await queryRunner.query(`COMMENT ON TABLE "user_role" IS 'Many-to-many relationship between user and roles'`);
        await queryRunner.query(`COMMENT ON TABLE "role" IS 'System roles for role-based access control'`);
        await queryRunner.query(`COMMENT ON TABLE "role_page" IS 'Role-based page access control'`);
        await queryRunner.query(`COMMENT ON TABLE "page" IS 'System pages/routes for navigation menu generation'`);
        await queryRunner.query(`COMMENT ON TABLE "layer" IS 'User-uploaded GeoJSON layers with PostGIS storage and sharing capabilities'`);
        await queryRunner.query(`COMMENT ON TABLE "layer_feature" IS 'Individual geometric features with PostGIS storage for spatial queries'`);
        await queryRunner.query(`CREATE INDEX "idx_layer_bbox" ON "layer" USING GiST ("bbox_geometry") `);
        await queryRunner.query(`CREATE INDEX "idx_layer_feature_geometry" ON "layer_feature" USING GiST ("geometry") `);
        await queryRunner.query(`ALTER TABLE "map" ADD CONSTRAINT "map_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "map" ADD CONSTRAINT "map_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "user_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "user_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "user_role_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "user_role_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "user_role_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "role_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "role_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_page" ADD CONSTRAINT "role_page_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_page" ADD CONSTRAINT "role_page_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "page"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_page" ADD CONSTRAINT "role_page_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page" ADD CONSTRAINT "page_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page" ADD CONSTRAINT "page_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layer" ADD CONSTRAINT "layer_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layer" ADD CONSTRAINT "layer_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layer" ADD CONSTRAINT "layer_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layer_feature" ADD CONSTRAINT "layer_feature_layer_id_fkey" FOREIGN KEY ("layer_id") REFERENCES "layer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
